"use strict";
exports.__esModule = true;
exports.DEFAULT_DEFENSE_POINTS_GENERATED = exports.DEFAULT_ATTACK_POINTS_GENERATED = exports.MAX_PLAYER_NUMBER = exports.DEFAULT_TOWER_DEFENSE = exports.DEFAULT_TOWER_HEALTH = void 0;
exports.DEFAULT_TOWER_HEALTH = 5000;
exports.DEFAULT_TOWER_DEFENSE = 2000;
exports.MAX_PLAYER_NUMBER = 2;
exports.DEFAULT_ATTACK_POINTS_GENERATED = 0;
exports.DEFAULT_DEFENSE_POINTS_GENERATED = 0;
